version: "3.9"

services:
  spark-master:
    image: bitnami/spark:4.0.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_LOG_LEVEL=INFO
      # History UI needs event logs
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:///opt/spark-events
    ports:
      - "7077:7077"   # cluster RPC
      - "8080:8080"   # Master UI
    volumes:
      - spark-events:/opt/spark-events
      - ./data:/data

  spark-worker-1:
    image: bitnami/spark:4.0.0
    container_name: spark-worker-1
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_LOG_LEVEL=WARN
      # Executors should run the Bitnami Python (3.12 in this image)
      - SPARK_WORKER_OPTS=-Dspark.executorEnv.PYSPARK_PYTHON=/opt/bitnami/python/bin/python
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python
    ports:
      - "8081:8081"   # Worker UI
    volumes:
      - ./data:/data

  spark-history:
    image: bitnami/spark:4.0.0
    container_name: spark-history
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark-events
    ports:
      - "18080:18080" # History UI
    volumes:
      - spark-events:/opt/spark-events

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: local/pyspark-notebook:spark-4.0.0-py31211
    container_name: spark-notebooks
    depends_on: [spark-master]
    environment:
      - JUPYTER_TOKEN=dev
      - SPARK_MASTER=spark://spark-master:7077
      # driver uses our py312 env by default because PATH points to it
      - PYSPARK_PYTHON=python
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data

volumes:
  spark-events:
